// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAPIKey(arg1:string):Promise<void>;

export function CancelLogin():Promise<void>;

export function ClearLogs():Promise<void>;

export function CopyText(arg1:string):Promise<void>;

export function DeleteAccount(arg1:string,arg2:string):Promise<void>;

export function GenerateAPIKey():Promise<string>;

export function GetAccessInfo():Promise<main.AccessView>;

export function GetLogs():Promise<Array<string>>;

export function GetState():Promise<main.StateView>;

export function HideWindow():Promise<void>;

export function OpenDataDir():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RefreshModels():Promise<void>;

export function RemoveAPIKey(arg1:string):Promise<void>;

export function ResetWindow():Promise<void>;

export function RestartService():Promise<void>;

export function SaveSettings(arg1:main.SettingsInput):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartLogin(arg1:string):Promise<main.LoginView>;

export function StartService():Promise<void>;

export function StopService():Promise<void>;

export function ToggleService():Promise<boolean>;
