// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAPIKey(arg1) {
  return window['go']['main']['App']['AddAPIKey'](arg1);
}

export function CancelLogin() {
  return window['go']['main']['App']['CancelLogin']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function DeleteAccount(arg1, arg2) {
  return window['go']['main']['App']['DeleteAccount'](arg1, arg2);
}

export function GenerateAPIKey() {
  return window['go']['main']['App']['GenerateAPIKey']();
}

export function GetAccessInfo() {
  return window['go']['main']['App']['GetAccessInfo']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RefreshModels() {
  return window['go']['main']['App']['RefreshModels']();
}

export function RemoveAPIKey(arg1) {
  return window['go']['main']['App']['RemoveAPIKey'](arg1);
}

export function ResetWindow() {
  return window['go']['main']['App']['ResetWindow']();
}

export function RestartService() {
  return window['go']['main']['App']['RestartService']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartLogin(arg1, arg2) {
  return window['go']['main']['App']['StartLogin'](arg1, arg2);
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function ToggleService() {
  return window['go']['main']['App']['ToggleService']();
}
